/**
 * De acht clusters van het voorbeeldaccount RunX, elk met 30 meetvragen.
 *
 * Plan: `docs/tasks/demo-account-runx.md` §5. De vragen zijn wat een prospect
 * in een demo het eerst herkent, dus ze staan er zoals een hardloper ze aan
 * ChatGPT stelt: met een plaatsnaam waar dat past (de regionale regel bij een
 * lokaal merk, `docs/architecture.md` §5), en verdeeld over oriëntatie,
 * overweging en beslissing (10, 10, 10).
 *
 * Puur, zonder `server-only`: de unittests tellen de vragen na.
 */

/** O = Oriëntatie, V = Overweging, B = Beslissing. */
export type Fase = "O" | "V" | "B";
/** Zoekvolume: hoog, midden, laag. Bepaalt het gewicht van de vraag in de score. */
export type Band = "h" | "m" | "l";

/** [fase, onderwerp binnen het cluster, vraag, volume] */
export type DemoVraag = readonly [Fase, string, string, Band];

export interface DemoCluster {
  sleutel: string;
  titel: string;
  /** Het onderwerp zoals het op de analyse staat; niet wijzigbaar na de start. */
  topic: string;
  rationale: string;
  /** Maand van de start, relatief aan de lopende maand (M0 = 0). */
  startMaand: number;
  herkomst: "aanbod_en_gesprek" | "ontdekking";
  /** Aanbodknopen (namen uit `merk.ts`) waar dit cluster over gaat. */
  aanbod: string[];
  /** Gewogen zichtbaarheid bij de nulmeting en nu, in procenten. */
  scoreStart: number;
  scoreNu: number;
  /** Concurrenten in volgorde van hoe vaak AI ze hier noemt, met hun aandeel bij de start en nu. */
  concurrenten: { naam: string; start: number; nu: number }[];
  /** Merken die RunX zelf voert en die AI in deze antwoorden noemt. */
  merken: string[];
  vragen: DemoVraag[];
}

export const CLUSTERS: DemoCluster[] = [
  {
    sleutel: "loopanalyse",
    titel: "Loopanalyse en de juiste hardloopschoen",
    topic: "loopanalyse laten doen en de juiste hardloopschoen kiezen",
    rationale:
      "De loopanalyse is waarmee RunX zich onderscheidt en wat lopers het vaakst als reden noemen om naar een speciaalzaak te gaan. Wie een loopanalyse zoekt, koopt meestal binnen twee weken schoenen.",
    startMaand: -13,
    herkomst: "aanbod_en_gesprek",
    aanbod: ["Loopanalyse", "Schoenadvies"],
    scoreStart: 4,
    scoreNu: 58,
    concurrenten: [
      { naam: "Run2Day", start: 38, nu: 27 },
      { naam: "Runnersworld", start: 22, nu: 17 },
      { naam: "Decathlon", start: 14, nu: 9 },
      { naam: "Intersport", start: 9, nu: 6 },
    ],
    merken: ["Asics", "Brooks", "Hoka", "Saucony"],
    vragen: [
      ["O", "Wat is een loopanalyse", "Wat is een loopanalyse en wat heb ik eraan als hardloper?", "h"],
      ["O", "Wat is een loopanalyse", "Is een loopanalyse in een hardloopwinkel zinvol of vooral verkooppraat?", "m"],
      ["O", "Loopanalyse fysio of winkel", "Wat is het verschil tussen een loopanalyse bij de fysiotherapeut en in een hardloopwinkel?", "m"],
      ["O", "Pronatie", "Hoe weet ik of ik overpronatie heb bij het hardlopen?", "h"],
      ["O", "Pronatie", "Heb ik een stabiele hardloopschoen nodig als mijn voeten naar binnen kantelen?", "m"],
      ["O", "Schoen kiezen", "Waar moet ik op letten bij het kiezen van mijn eerste echte hardloopschoenen?", "h"],
      ["O", "Schoen kiezen", "Hoeveel demping heb ik nodig in een hardloopschoen?", "m"],
      ["O", "Schoen kiezen", "Wat betekent de drop van een hardloopschoen en maakt het uit?", "l"],
      ["O", "Wat is een loopanalyse", "Hoe lang duurt een loopanalyse en wat gebeurt er precies?", "l"],
      ["O", "Schoen kiezen", "Moet ik mijn hardloopschoenen een halve maat groter kopen?", "m"],
      ["V", "Loopanalyse per stad", "Waar kan ik een loopanalyse laten doen in Apeldoorn?", "m"],
      ["V", "Loopanalyse per stad", "Waar kan ik een loopanalyse laten doen in Groningen?", "m"],
      ["V", "Loopanalyse per stad", "Waar kan ik een loopanalyse laten doen in Haarlem?", "m"],
      ["V", "Loopanalyse per stad", "Waar kan ik een loopanalyse laten doen in Tilburg?", "m"],
      ["V", "Loopanalyse per stad", "Waar kan ik een loopanalyse laten doen in Enschede?", "m"],
      ["V", "Loopanalyse per stad", "Waar kan ik een loopanalyse laten doen in Zaandam?", "m"],
      ["V", "Gratis loopanalyse", "Welke hardloopwinkels doen een gratis loopanalyse?", "h"],
      ["V", "Schoen kiezen", "Asics Gel-Kayano of Brooks Adrenaline: welke stabiele schoen past bij mij?", "l"],
      ["V", "Schoen kiezen", "Hoka of On: wat is het verschil voor een recreatieve loper?", "m"],
      ["V", "Loopanalyse fysio of winkel", "Loopanalyse op een loopband of buiten: wat is betrouwbaarder?", "l"],
      ["B", "Loopanalyse per stad", "Beste hardloopwinkel met loopanalyse in de regio Twente", "m"],
      ["B", "Loopanalyse per stad", "Hardloopschoenen kopen met advies in Haarlem", "m"],
      ["B", "Loopanalyse per stad", "Hardloopschoenen kopen met loopanalyse in Apeldoorn of Deventer", "m"],
      ["B", "Loopanalyse per stad", "Waar koop ik hardloopschoenen met goed advies in Groningen?", "m"],
      ["B", "Loopanalyse per stad", "Hardloopwinkel in de Zaanstreek met loopanalyse", "l"],
      ["B", "Loopanalyse per stad", "Hardloopschoenen passen en testen in Tilburg", "l"],
      ["B", "Gratis loopanalyse", "Moet ik een afspraak maken voor een loopanalyse in de winkel?", "l"],
      ["B", "Schoen kiezen", "Kan ik hardloopschoenen ruilen als ze na een paar keer lopen toch niet goed zitten?", "m"],
      ["B", "Gratis loopanalyse", "Wat kost een loopanalyse bij een hardloopwinkel?", "h"],
      ["B", "Schoen kiezen", "Online hardloopschoenen kopen of in de winkel passen?", "m"],
    ],
  },
  {
    sleutel: "schoenen",
    titel: "Hardloopschoenen kiezen per loper",
    topic: "hardloopschoenen kiezen voor jouw type loper en ondergrond",
    rationale:
      "Schoenen zijn het grootste deel van de omzet. De vragen gaan over het moment vóór de winkel: welke soort schoen, welk merk, hoe vaak vervangen.",
    startMaand: -13,
    herkomst: "aanbod_en_gesprek",
    aanbod: ["Hardloopschoenen", "Neutrale hardloopschoenen", "Stabiele hardloopschoenen", "Hardloopkleding"],
    scoreStart: 7,
    scoreNu: 41,
    concurrenten: [
      { naam: "Zalando", start: 26, nu: 18 },
      { naam: "Run2Day", start: 24, nu: 19 },
      { naam: "Decathlon", start: 18, nu: 13 },
      { naam: "Bol", start: 11, nu: 8 },
    ],
    merken: ["Asics", "Brooks", "Hoka", "On", "Saucony", "New Balance", "Mizuno"],
    vragen: [
      ["O", "Hoe vaak vervangen", "Hoe vaak moet ik mijn hardloopschoenen vervangen?", "h"],
      ["O", "Hoe vaak vervangen", "Hoe zie je dat hardloopschoenen versleten zijn?", "m"],
      ["O", "Zware lopers", "Welke hardloopschoenen zijn goed voor zwaardere lopers?", "m"],
      ["O", "Brede voeten", "Welke hardloopschoenen passen bij brede voeten?", "m"],
      ["O", "Ondergrond", "Kan ik met gewone hardloopschoenen ook op onverharde paden lopen?", "l"],
      ["O", "Max demping", "Zijn schoenen met maximale demping beter voor je knieën?", "m"],
      ["O", "Herfst en regen", "Welke hardloopschoenen hebben goede grip op natte straten?", "l"],
      ["O", "Kleding", "Wat trek je aan bij het hardlopen in de herfst?", "m"],
      ["O", "Kleding", "Wat is het verschil tussen hardloopsokken en gewone sokken?", "l"],
      ["O", "Max demping", "Wat is een rocker in een hardloopschoen?", "l"],
      ["V", "Merken vergelijken", "Brooks Ghost of Asics Novablast: welke is beter voor dagelijkse trainingen?", "m"],
      ["V", "Merken vergelijken", "Is de Hoka Clifton geschikt voor beginners?", "m"],
      ["V", "Merken vergelijken", "Saucony Endorphin Azura of Speed: wat is het verschil?", "l"],
      ["V", "Merken vergelijken", "Brooks Glycerin of Hoka Bondi voor lange duurlopen?", "l"],
      ["V", "Twee paar", "Is het slim om twee paar hardloopschoenen af te wisselen?", "m"],
      ["V", "Zware lopers", "Beste hardloopschoen voor lopers boven de 90 kilo", "m"],
      ["V", "Brede voeten", "Welke merken maken hardloopschoenen in een brede leest?", "l"],
      ["V", "Herfst en regen", "Zijn waterdichte hardloopschoenen met Gore-Tex het waard?", "l"],
      ["V", "Kleding", "Welke hardloopjas is echt waterdicht en ademend?", "m"],
      ["V", "Merken vergelijken", "Nieuwe hardloopschoenen van 2026: wat is echt beter geworden?", "m"],
      ["B", "Kopen", "Waar koop ik Hoka hardloopschoenen met advies in de buurt van Haarlem?", "l"],
      ["B", "Kopen", "Waar kan ik Brooks hardloopschoenen passen in Groningen?", "l"],
      ["B", "Kopen", "Hardloopwinkel met groot aanbod On en Saucony in Tilburg", "l"],
      ["B", "Kopen", "Waar kan ik Asics hardloopschoenen proberen in Apeldoorn?", "l"],
      ["B", "Kopen", "Brede hardloopschoenen passen in Enschede", "l"],
      ["B", "Kopen", "Hardloopschoenen kopen in Zaandam", "m"],
      ["B", "Kopen", "Beste hardloopwinkel van Nederland voor schoenadvies", "h"],
      ["B", "Kopen", "Hardloopschoenen in de uitverkoop: waar moet ik op letten?", "m"],
      ["B", "Kopen", "Hardloopschoenen van vorig seizoen kopen: is dat slim?", "l"],
      ["B", "Kopen", "Speciaalzaak of sportwinkel voor hardloopschoenen?", "m"],
    ],
  },
  {
    sleutel: "blessures",
    titel: "Blessures voorkomen en herstel",
    topic: "hardloopblessures voorkomen en goed herstellen",
    rationale:
      "Lopers met klachten zoeken eerst online en gaan daarna vaak naar een speciaalzaak voor een andere schoen, compressie of zooltjes. RunX verwijst door waar nodig; dat maakt het advies geloofwaardig.",
    startMaand: -13,
    herkomst: "aanbod_en_gesprek",
    aanbod: ["Compressie", "Sokken- en zooladvies", "Loopanalyse"],
    scoreStart: 2,
    scoreNu: 29,
    concurrenten: [
      { naam: "Decathlon", start: 19, nu: 15 },
      { naam: "Run2Day", start: 17, nu: 14 },
      { naam: "Bol", start: 10, nu: 8 },
      { naam: "Runnersworld", start: 9, nu: 7 },
    ],
    merken: ["Herzog", "CEP", "Asics", "Brooks"],
    vragen: [
      ["O", "Scheenbeen", "Wat zijn shin splints en hoe kom je ervan af?", "h"],
      ["O", "Scheenbeen", "Kan een andere hardloopschoen helpen tegen scheenbeenklachten?", "m"],
      ["O", "Knie", "Waarom krijg ik pijn aan de buitenkant van mijn knie bij hardlopen?", "h"],
      ["O", "Achillespees", "Hoe voorkom je achillespeesklachten bij het hardlopen?", "m"],
      ["O", "Compressie", "Werken compressiekousen echt bij hardlopen?", "m"],
      ["O", "Herstel", "Hoeveel rustdagen heb je nodig na een lange duurloop?", "m"],
      ["O", "Herstel", "Wat eet je na een zware training voor het beste herstel?", "m"],
      ["O", "Opbouw", "Hoe snel mag je je kilometers opbouwen zonder blessure?", "h"],
      ["O", "Fasciitis", "Wat helpt tegen hielpijn bij hardlopers?", "m"],
      ["O", "Opbouw", "Is krachttraining nodig voor hardlopers?", "m"],
      ["V", "Compressie", "Compressiekousen of compressiesleeves: wat is beter voor herstel?", "l"],
      ["V", "Zolen", "Helpen inlegzolen tegen hardloopblessures?", "m"],
      ["V", "Knie", "Welke hardloopschoen is goed bij knieklachten?", "m"],
      ["V", "Achillespees", "Welke drop is beter bij achillespeesklachten?", "l"],
      ["V", "Herstel", "Foamrollen of massage: wat helpt hardlopers meer?", "l"],
      ["V", "Opbouw", "Hardlopen met een blessure: wanneer moet je stoppen?", "m"],
      ["V", "Scheenbeen", "Fysiotherapeut of hardloopwinkel bij scheenbeenklachten?", "l"],
      ["V", "Leeftijd", "Waar moet je op letten als je na je veertigste gaat hardlopen?", "m"],
      ["V", "Leeftijd", "Hardlopen na je vijftigste: welke schoenen en welke opbouw?", "l"],
      ["V", "Herstel", "Herstelschoenen of slippers na het hardlopen: zin of onzin?", "l"],
      ["B", "Advies in de buurt", "Waar krijg ik hardloopadvies bij blessures in Tilburg?", "l"],
      ["B", "Advies in de buurt", "Compressiekousen kopen met advies in Apeldoorn", "l"],
      ["B", "Advies in de buurt", "Hardloopwinkel met kennis van blessures in Haarlem", "l"],
      ["B", "Advies in de buurt", "Waar kan ik compressiekousen laten aanmeten in Groningen?", "l"],
      ["B", "Advies in de buurt", "Loopanalyse na een blessure in Enschede", "l"],
      ["B", "Advies in de buurt", "Inlegzolen voor hardlopen kopen in Zaandam", "l"],
      ["B", "Compressie", "Beste compressiekousen voor hardlopers in 2026", "m"],
      ["B", "Zolen", "Waar koop ik goede hardloopzolen met advies?", "m"],
      ["B", "Knie", "Beste hardloopschoen voor lopers met knieklachten", "m"],
      ["B", "Herstel", "Welke herstelproducten raden hardloopwinkels aan?", "l"],
    ],
  },
  {
    sleutel: "stad",
    titel: "Hardlopen in je eigen stad",
    topic: "hardloopwinkels, routes en loopgroepen in de zes RunX-steden",
    rationale:
      "Zes winkels, zes regio's. Wie in zijn eigen stad een winkel, een route of een loopgroep zoekt, is de klant die het dichtst bij de winkeldeur staat.",
    startMaand: -13,
    herkomst: "aanbod_en_gesprek",
    aanbod: ["Vestigingen", "Trainingen en trainingsgroepen", "RunX Club"],
    scoreStart: 9,
    scoreNu: 52,
    concurrenten: [
      { naam: "Run2Day", start: 36, nu: 26 },
      { naam: "Runnersworld", start: 24, nu: 18 },
      { naam: "Intersport", start: 12, nu: 8 },
      { naam: "Decathlon", start: 10, nu: 7 },
    ],
    merken: ["Garmin", "Strava"],
    vragen: [
      ["O", "Routes", "Mooie hardlooprondes rond Apeldoorn", "m"],
      ["O", "Routes", "Waar kun je goed hardlopen in Groningen?", "m"],
      ["O", "Routes", "Mooie hardlooproutes in de duinen bij Haarlem", "m"],
      ["O", "Routes", "Hardlooproutes rond Tilburg met onverhard pad", "l"],
      ["O", "Routes", "Mooie hardlooproutes in Twente", "m"],
      ["O", "Routes", "Waar loop je hard in Zaandam en omgeving?", "l"],
      ["O", "Loopgroepen", "Hoe vind ik een hardloopgroep in mijn buurt?", "m"],
      ["O", "Loopgroepen", "Wat is het verschil tussen een atletiekvereniging en een loopgroep van een winkel?", "l"],
      ["O", "Events", "Welke hardloopwedstrijden zijn er in het najaar in Noord-Holland?", "m"],
      ["O", "Events", "Leuke hardloopevenementen in Oost-Nederland", "l"],
      ["V", "Loopgroepen", "Hardlooptrainingsgroep voor beginners in Haarlem", "m"],
      ["V", "Loopgroepen", "Hardloopgroep in Groningen voor recreanten", "m"],
      ["V", "Loopgroepen", "Samen hardlopen in Tilburg op doordeweekse avonden", "l"],
      ["V", "Loopgroepen", "Loopgroep in Apeldoorn voor de Midwinter Marathon", "l"],
      ["V", "Loopgroepen", "Trailgroep in Twente", "l"],
      ["V", "Loopgroepen", "Hardlopen met een groep in de Zaanstreek", "l"],
      ["V", "Winkels", "Wat zijn de beste hardloopspeciaalzaken in Oost-Nederland?", "m"],
      ["V", "Winkels", "Hardloopwinkel met eigen community en events", "l"],
      ["V", "Winkels", "Welke hardloopketen heeft de meeste winkels in Nederland?", "m"],
      ["V", "Events", "Wat zijn goede voorbereidingslopen voor de Dam tot Damloop?", "l"],
      ["B", "Winkels", "Beste hardloopwinkel in Apeldoorn", "m"],
      ["B", "Winkels", "Beste hardloopwinkel in Groningen", "m"],
      ["B", "Winkels", "Beste hardloopwinkel in Haarlem", "m"],
      ["B", "Winkels", "Beste hardloopwinkel in Tilburg", "m"],
      ["B", "Winkels", "Beste hardloopwinkel in Enschede of Hengelo", "m"],
      ["B", "Winkels", "Beste hardloopwinkel in Zaandam", "m"],
      ["B", "Winkels", "Hardloopwinkel open op zondag in Haarlem", "l"],
      ["B", "Winkels", "Hardloopwinkel met parkeren voor de deur in Apeldoorn", "l"],
      ["B", "Loopgroepen", "Hoe word ik lid van een loopgroep van een hardloopwinkel?", "l"],
      ["B", "Winkels", "Hardloopwinkel in de buurt van Amsterdam-Noord", "m"],
    ],
  },
  {
    sleutel: "beginnen",
    titel: "Beginnen met hardlopen",
    topic: "beginnen met hardlopen, van nul naar vijf kilometer",
    rationale:
      "Elk jaar in januari begint een grote groep met hardlopen. Wie goed begint, komt terug voor de volgende schoen. Voor RunX de instroom van nieuwe klanten.",
    startMaand: -10,
    herkomst: "aanbod_en_gesprek",
    aanbod: ["Trainingen en trainingsgroepen", "Hardloopschoenen", "RunX Club"],
    scoreStart: 3,
    scoreNu: 33,
    concurrenten: [
      { naam: "Decathlon", start: 24, nu: 18 },
      { naam: "Run2Day", start: 15, nu: 12 },
      { naam: "Start to Run", start: 14, nu: 11 },
      { naam: "Zalando", start: 8, nu: 6 },
    ],
    merken: ["Asics", "Brooks", "Garmin"],
    vragen: [
      ["O", "Eerste weken", "Hoe begin ik met hardlopen als ik nog nooit gerend heb?", "h"],
      ["O", "Eerste weken", "Hoe vaak per week moet je hardlopen als beginner?", "h"],
      ["O", "Eerste weken", "Hoe lang duurt het om vijf kilometer te kunnen hardlopen?", "h"],
      ["O", "Eerste weken", "Waarom raak ik zo snel buiten adem bij het hardlopen?", "m"],
      ["O", "Schema", "Is een schema van nul naar vijf kilometer echt haalbaar in acht weken?", "m"],
      ["O", "Uitrusting", "Wat heb je nodig om te beginnen met hardlopen?", "h"],
      ["O", "Uitrusting", "Kan ik beginnen met hardlopen op gewone sportschoenen?", "m"],
      ["O", "Motivatie", "Hoe houd je het vol om te blijven hardlopen?", "m"],
      ["O", "Gewicht", "Hardlopen met overgewicht: hoe begin je verantwoord?", "m"],
      ["O", "Eerste weken", "Hardlopen in de ochtend of in de avond als beginner?", "l"],
      ["V", "Schema", "Beste hardloopapp voor beginners", "h"],
      ["V", "Schema", "Alleen beginnen met een app of in een beginnersgroep?", "m"],
      ["V", "Uitrusting", "Goedkope of dure hardloopschoenen als beginner?", "m"],
      ["V", "Uitrusting", "Heb je een sporthorloge nodig als beginnende hardloper?", "m"],
      ["V", "Uitrusting", "Welke hardloopschoenen zijn het best voor beginners?", "h"],
      ["V", "Motivatie", "Een doel stellen als beginnende hardloper: welke eerste wedstrijd?", "l"],
      ["V", "Gewicht", "Welke hardloopschoenen voor beginners met overgewicht?", "m"],
      ["V", "Schema", "Interval of rustig doorlopen als beginner?", "l"],
      ["V", "Uitrusting", "Welke hardloopkleding heb je echt nodig als beginner?", "m"],
      ["V", "Eerste weken", "Spierpijn na de eerste keer hardlopen: doorgaan of rusten?", "l"],
      ["B", "Groep zoeken", "Beginnersgroep hardlopen in Haarlem in januari", "l"],
      ["B", "Groep zoeken", "Start to run cursus in Groningen", "m"],
      ["B", "Groep zoeken", "Beginnen met hardlopen in een groep in Apeldoorn", "l"],
      ["B", "Groep zoeken", "Beginnerstraining hardlopen in Tilburg", "l"],
      ["B", "Groep zoeken", "Hardlopen voor beginners in Enschede", "l"],
      ["B", "Groep zoeken", "Beginnen met hardlopen in Zaandam", "l"],
      ["B", "Schoenen kopen", "Waar koop ik mijn eerste hardloopschoenen met advies?", "h"],
      ["B", "Schoenen kopen", "Beginnersset hardlopen kopen: schoenen, sokken en shirt", "l"],
      ["B", "Schoenen kopen", "Eerste hardloopschoenen kopen in de buurt van Amsterdam", "m"],
      ["B", "Groep zoeken", "Wat kost een beginnerscursus hardlopen?", "m"],
    ],
  },
  {
    sleutel: "wedstrijd",
    titel: "Wedstrijdschoenen en racen",
    topic: "wedstrijdschoenen en de voorbereiding op een marathon, halve marathon of tien mijl",
    rationale:
      "Wedstrijdschoenen zijn de duurste aankoop en de vraag waar lopers het meest advies bij zoeken. De events in de eigen regio (Midwinter Marathon, Enschede Marathon, Tilburg Ten Miles, Dam tot Damloop, 4 Mijl van Groningen) geven elk jaar vaste momenten.",
    startMaand: -8,
    herkomst: "aanbod_en_gesprek",
    aanbod: ["Wedstrijdschoenen", "Voeding", "Events"],
    scoreStart: 5,
    scoreNu: 36,
    concurrenten: [
      { naam: "Run2Day", start: 29, nu: 22 },
      { naam: "Zalando", start: 15, nu: 11 },
      { naam: "Runnersworld", start: 14, nu: 11 },
      { naam: "Sportsdirect", start: 6, nu: 4 },
    ],
    merken: ["Saucony", "Nike", "Asics", "Adidas", "Maurten", "Hoka"],
    vragen: [
      ["O", "Carbon", "Wat doet een carbon plaat in een hardloopschoen?", "h"],
      ["O", "Carbon", "Is een carbon schoen zinvol voor een recreatieve marathonloper?", "m"],
      ["O", "Carbon", "Hoeveel kilometer gaat een wedstrijdschoen mee?", "m"],
      ["O", "Voorbereiding", "Hoe bereid je je de laatste vier weken voor op een marathon?", "h"],
      ["O", "Voorbereiding", "Wat is taperen en hoe doe je het goed?", "m"],
      ["O", "Voeding", "Hoeveel energiegels heb je nodig tijdens een marathon?", "m"],
      ["O", "Voeding", "Wat eet je de avond voor een halve marathon?", "m"],
      ["O", "Tempo", "Hoe bepaal je je wedstrijdtempo voor een halve marathon?", "m"],
      ["O", "Tempo", "Wat is een goede tijd voor tien Engelse mijl?", "l"],
      ["O", "Voorbereiding", "Hoe loop je een nieuwe wedstrijdschoen in?", "l"],
      ["V", "Carbon", "Saucony Endorphin Elite of Nike Vaporfly: welke past bij mij?", "m"],
      ["V", "Carbon", "Asics Metaspeed Sky of Edge: wat is het verschil?", "l"],
      ["V", "Carbon", "Adidas Adios Pro of Hoka Rocket X voor een marathon?", "l"],
      ["V", "Carbon", "Supershoe of gewone tempo schoen voor een halve marathon?", "m"],
      ["V", "Voeding", "Maurten of SiS gels: welke werken beter?", "l"],
      ["V", "Events", "Midwinter Marathon Apeldoorn: wat moet je weten over het parcours?", "m"],
      ["V", "Events", "Enschede Marathon: hoe bereid je je voor?", "m"],
      ["V", "Events", "Tilburg Ten Miles: snel parcours of niet?", "l"],
      ["V", "Events", "4 Mijl van Groningen: hoe loop je een snelle tijd?", "m"],
      ["V", "Events", "Dam tot Damloop: tips voor de finish in Zaandam", "m"],
      ["B", "Kopen", "Waar kan ik carbon wedstrijdschoenen passen in Apeldoorn?", "l"],
      ["B", "Kopen", "Wedstrijdschoenen kopen met advies in Groningen", "l"],
      ["B", "Kopen", "Wedstrijdschoenen testen in Haarlem", "l"],
      ["B", "Kopen", "Saucony Endorphin kopen in Tilburg", "l"],
      ["B", "Kopen", "Carbon schoenen proberen in Enschede", "l"],
      ["B", "Kopen", "Wedstrijdschoenen kopen in de Zaanstreek", "l"],
      ["B", "Kopen", "Beste wedstrijdschoen voor een marathon onder de 3u30", "m"],
      ["B", "Kopen", "Beste wedstrijdschoen voor beginners op de halve marathon", "m"],
      ["B", "Voeding", "Waar koop ik sportvoeding voor de marathon?", "m"],
      ["B", "Kopen", "Wedstrijdschoen in de aanbieding na het seizoen", "l"],
    ],
  },
  {
    sleutel: "trail",
    titel: "Trailrunning op de Veluwe en in Twente",
    topic: "trailrunning: schoenen, uitrusting en routes in Oost-Nederland",
    rationale:
      "Trailrunning groeit, en twee van de zes winkels liggen naast de beste trailgebieden van Nederland. Trailschoenen en rugzakken hebben een hogere bonwaarde dan gemiddeld.",
    startMaand: -5,
    herkomst: "aanbod_en_gesprek",
    aanbod: ["Trailschoenen", "Rugzakken en heuptassen"],
    scoreStart: 1,
    scoreNu: 24,
    concurrenten: [
      { naam: "Bever", start: 22, nu: 17 },
      { naam: "Decathlon", start: 20, nu: 15 },
      { naam: "Run2Day", start: 13, nu: 10 },
      { naam: "Zalando", start: 7, nu: 5 },
    ],
    merken: ["Hoka", "Salomon", "Saucony", "Brooks"],
    vragen: [
      ["O", "Beginnen", "Hoe begin je met trailrunning?", "m"],
      ["O", "Beginnen", "Wat is het verschil tussen trailrunning en gewoon hardlopen?", "m"],
      ["O", "Schoenen", "Heb je echt trailschoenen nodig voor bospaden?", "m"],
      ["O", "Schoenen", "Wat is een goede nopdiepte voor trailschoenen in Nederland?", "l"],
      ["O", "Uitrusting", "Wat neem je mee op een lange trailrun?", "m"],
      ["O", "Techniek", "Hoe loop je goed bergaf op een trail?", "l"],
      ["O", "Routes", "Mooie trailroutes op de Veluwe", "m"],
      ["O", "Routes", "Trailrunnen in Twente: waar begin je?", "l"],
      ["O", "Routes", "Is de Holterberg geschikt voor trailtraining?", "l"],
      ["O", "Beginnen", "Trailrunning in de herfst en winter: waar moet je op letten?", "l"],
      ["V", "Schoenen", "Hoka Speedgoat of Salomon Speedcross voor modderige paden?", "m"],
      ["V", "Schoenen", "Saucony Peregrine of Brooks Cascadia: welke trailschoen kies ik?", "l"],
      ["V", "Schoenen", "Waterdichte trailschoenen of juist niet?", "l"],
      ["V", "Uitrusting", "Hardlooprugzak of heuptas voor een trail van 20 kilometer?", "m"],
      ["V", "Uitrusting", "Beste hardloopvest met drinkflessen", "l"],
      ["V", "Uitrusting", "Welk horloge is goed voor trailrunning met navigatie?", "m"],
      ["V", "Beginnen", "Trailwedstrijd voor beginners in Oost-Nederland", "l"],
      ["V", "Routes", "Trailrun op de Posbank: hoe zwaar is het?", "l"],
      ["V", "Techniek", "Stokken bij trailrunning: wanneer zinvol?", "l"],
      ["V", "Schoenen", "Kun je trailschoenen ook op asfalt gebruiken?", "l"],
      ["B", "Kopen", "Trailschoenen kopen met advies in Apeldoorn", "l"],
      ["B", "Kopen", "Trailschoenen passen in Enschede", "l"],
      ["B", "Kopen", "Waar koop ik een hardlooprugzak in Twente?", "l"],
      ["B", "Kopen", "Trailschoenen kopen in de buurt van de Veluwe", "l"],
      ["B", "Kopen", "Beste trailschoen voor beginners in 2026", "m"],
      ["B", "Kopen", "Speciaalzaak voor trailrunning in Oost-Nederland", "l"],
      ["B", "Kopen", "Trailschoenen testen voordat je ze koopt", "l"],
      ["B", "Groep", "Trailtraining met een groep op de Veluwe", "l"],
      ["B", "Groep", "Trailclinic voor beginners in Twente", "l"],
      ["B", "Kopen", "Trailschoenen kopen in Tilburg voor de Loonse en Drunense Duinen", "l"],
    ],
  },
  {
    sleutel: "hyrox",
    titel: "HYROX: training, schoenen en uitrusting",
    topic: "HYROX: trainen, schoenen en uitrusting voor hardlopers",
    rationale:
      "Gevonden met Clusters ontdekken in augustus 2026: snel groeiende zoekvraag, en de bestaande blog over HYROX deed het al opvallend goed. Een nieuwe groep sporters die hardlopen combineert met kracht.",
    startMaand: -2,
    herkomst: "ontdekking",
    aanbod: ["Hardloopschoenen", "Trainingen en trainingsgroepen"],
    scoreStart: 3,
    scoreNu: 14,
    concurrenten: [
      { naam: "Decathlon", start: 18, nu: 16 },
      { naam: "Run2Day", start: 10, nu: 9 },
      { naam: "Zalando", start: 9, nu: 8 },
      { naam: "Basic-Fit", start: 12, nu: 11 },
    ],
    merken: ["Asics", "Nike", "Puma", "On"],
    vragen: [
      ["O", "Wat is HYROX", "Wat is HYROX en hoe werkt een wedstrijd?", "h"],
      ["O", "Wat is HYROX", "Hoeveel kilometer loop je bij HYROX?", "m"],
      ["O", "Training", "Hoe train je voor je eerste HYROX?", "h"],
      ["O", "Training", "Hoeveel weken voorbereiding heb je nodig voor HYROX?", "m"],
      ["O", "Training", "Hardlopen combineren met krachttraining voor HYROX", "m"],
      ["O", "Schoenen", "Welke schoenen draag je bij HYROX?", "h"],
      ["O", "Schoenen", "Hardloopschoen of trainingsschoen voor HYROX?", "m"],
      ["O", "Wat is HYROX", "Is HYROX geschikt voor hardlopers zonder crossfitervaring?", "m"],
      ["O", "Training", "Hoe verbeter je je looptempo na de sled push?", "l"],
      ["O", "Uitrusting", "Wat trek je aan bij een HYROX-wedstrijd?", "l"],
      ["V", "Schoenen", "Beste HYROX-schoen van 2026", "m"],
      ["V", "Schoenen", "Asics Novablast of Nike Pegasus voor HYROX?", "l"],
      ["V", "Schoenen", "Puma Deviate Nitro voor HYROX: goede keuze?", "l"],
      ["V", "Schoenen", "On Cloudmonster voor HYROX of te veel demping?", "l"],
      ["V", "Training", "HYROX-schema voor hardlopers die al tien kilometer lopen", "m"],
      ["V", "Training", "Doubles of solo bij je eerste HYROX?", "l"],
      ["V", "Uitrusting", "Handschoenen bij HYROX: nodig of niet?", "l"],
      ["V", "Uitrusting", "Compressiekleding bij HYROX", "l"],
      ["V", "Training", "Sportschool of loopgroep voor HYROX-training?", "l"],
      ["V", "Wat is HYROX", "HYROX in Nederland: waar en wanneer?", "m"],
      ["B", "Kopen", "Waar koop ik HYROX-schoenen met advies in Zaandam?", "l"],
      ["B", "Kopen", "HYROX-schoenen passen in Haarlem", "l"],
      ["B", "Kopen", "HYROX-schoenen kopen in Groningen", "l"],
      ["B", "Kopen", "HYROX-schoenen kopen in Tilburg", "l"],
      ["B", "Kopen", "HYROX-schoenen kopen in Apeldoorn", "l"],
      ["B", "Kopen", "HYROX-schoenen kopen in Enschede", "l"],
      ["B", "Training", "HYROX-loopgroep bij een hardloopwinkel", "l"],
      ["B", "Training", "HYROX-trainingen in de regio Amsterdam", "m"],
      ["B", "Kopen", "Beste winkel voor HYROX-uitrusting", "l"],
      ["B", "Kopen", "Schoenen voor HYROX en hardlopen in één", "m"],
    ],
  },
];
